### ISSUE TITLE
FIX does not work in Firefox 76

### ISSUE THREAD

**Issue by allanlaal** [ris58h/youtube-timestamps#10]
addon version 0.1.10

**Comment by ris58h** [comment]
Could you elaborate more?

**Comment by allanlaal** [comment]
does not show any youtube timestamp comments, whereas YouTube Live Comments shows them

what information do you need to debug this?

**Comment by ris58h** [comment]
Did the extension work for you in previous versions of FF?
I have FF 74 now, so should I install Nightly or Beta to check it?

**Comment by allanlaal** [comment]
install firefox-trunk, that'll give you 76

I havent tested it with 74. the last time I used it was 60 sth

**Comment by ris58h** [comment]
I've installed FF Nightly on macOS (same as firefox-trunk on Linux I suppose) and it works well.
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/511242/78258272-a6ae1680-7503-11ea-8ece-9eadc73b74a0.png">

Do you have any errors in console?
