### ISSUE TITLE
[bug] not showing the comments but showing only the white timeline marks

### ISSUE THREAD

**Issue by paulolimac** [ris58h/youtube-timestamps#14]
The extension is showing only the white marks on Youtube's timeline videos.
But it isn't showing the comments over the mini-screen/thumbnails.
I think this bug started today.

And thanks for your extension! It is really useful.

**Comment by ris58h** [comment]
Thank you for your feedback!
I've reproduced the issue. I'll try to fix tomorrow.

**Comment by ris58h** [comment]
@paulolimac It should work in 0.1.12

**Comment by paulolimac** [comment]
worked like a charm!
thank you very much for your fast fixing.
:)
