### ISSUE TITLE
Won't show any timestamps on youtube video...

### ISSUE THREAD

**Issue by Tendas240** [ris58h/youtube-timestamps#17]
I can't see any timestamps appearing in the progress bar. It doesn't show anything and there are enough comments with timestamps in them...

Any alternative to this extension? It seems like it doesn't work anymore because first the video loads and only if you scroll down the comments will show. Maybe thats the issue but i can imagine many people already called that one out.

**Comment by ris58h** [comment]
Hi.

It seems like a problem with [quota](https://developers.google.com/youtube/v3/getting-started#quota).
<img width="867" alt="image" src="https://user-images.githubusercontent.com/511242/113352644-3e2b8c80-9345-11eb-99cc-6a7d192a0d8f.png">

The extension doesn't use the comments from the web-page but loads them using YouTube API. Unfortunately, Google lowered the quota for the YouTube API, which is used by the extension. They reset it everyday at midnight Pacific Time, so if you live in the US, there is probably just no quota left at the time you use the extension. Sorry.

I still haven't find a solution that would be convenient for users.

**Comment by Tendas240** [comment]
> Hi.
> 
> It seems like a problem with [quota](https://developers.google.com/youtube/v3/getting-started#quota).
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/511242/113352644-3e2b8c80-9345-11eb-99cc-6a7d192a0d8f.png">
> 
> The extension doesn't use the comments from the web-page but loads them using YouTube API. Unfortunately, Google lowered the quota for the YouTube API, which is used by the extension. They reset it everyday at midnight Pacific Time, so if you live in the US, there is probably just no quota left at the time you use the extension. Sorry.
> 
> I still haven't find a solution that would be convenient for users.

Hey.

Okay thank you for your response. No im german and therefore its cet for me but that probably doesnt change anything in that situation. The extension doesnt work. Pretty sad because it'd find it very useful. But you can keep me up to date if you plan on developing something similar in the future ^^

**Comment by ris58h** [comment]
I've managed to use internal YT API to not to spend the quota. Check it out!
