### ISSUE TITLE
Hormonize add-on with new youtube feature

### ISSUE THREAD

**Issue by samwolfe2000** [ris58h/youtube-timestamps#19]
Youtube recently has added a very simular function which could work well together with this addon if small adjustments were made.

This new YT function looks a bit different (a bit more modern i guess), but does prettymuch the same, except, it only shows timestamps placed in the discription and in the beginning of a row. 

I wonder if you could adjust the addon to this new feature by exluding timestamps having this new functionality. It would make the timeline more transparent in some cases.

Regards,

Samwolfe

**Comment by ris58h** [comment]
Hi @samwolfe2000 this has been fixed in version 0.2.2 (already available for Firefox and on review at this moment for Chrome).

**Comment by samwolfe2000** [comment]
Hi (sorry, I forgot to say hello), 

Thanks for your efforts, unfortunatelly I can't notice a difference on Firefox. Have you a clue what's this?

Sam

**Comment by ris58h** [comment]
@samwolfe2000 make sure you have 0.2.2 version of the add-on. If true, send me a link on the video page where it doesn't work so I could check what's wrong.

**Comment by samwolfe2000** [comment]
It's a longer one: https://www.youtube.com/watch?v=aoajtl7BSe0

Ilya Rodionov ***@***.***> ezt írta (időpont: 2021. jún. 24.,
Cs, 21:33):

**Comment by ris58h** [comment]
Oh. I see.
It looks like the reason is ending chapter timestamps. The easiest way to fix it is not to show timestamps from the description at all. Most of them a chapter timestamps anyway. But in rare cases there could be timestamps in the description that aren't about chapters.

**Comment by ris58h** [comment]
Since version 0.2.3 the extension doesn't show timestamps from a description.

**Comment by samwolfe2000** [comment]
Yes, I think this solution is fine.

Ilya Rodionov ***@***.***> ezt írta (időpont: 2021. jún. 26.,
Szo, 17:28):
