### ISSUE TITLE
Add support for Invidious

### ISSUE THREAD

**Issue by Smokey137** [ris58h/youtube-timestamps#22]
Hello,

Is it possible to add support for alternative front-end YouTube instances such as Invidious?

**Comment by ris58h** [comment]
Hi! I haven't heard about that project before. I've checked it quickly and it seems like they use their own API and the HTML layout of video page is different (sometimes even for different servers). It's a good amount of work to support all of that.
Probably it would be better to solve the issue by creating a separate add-on.
