### ISSUE TITLE
It is impossible to view timestamps if video is over and it is ongoing timer before another video

### ISSUE THREAD

**Issue by S-trace** [ris58h/youtube-timestamps#23]
Hello.

If the video you watched has reached its end - youtube shows a countdown for another video.
It is impossible to view timestamped comments at this state of the player.

I think it will be useful if user will be able to view timestamped comments after watching the video and the countdown for the next video will be reset or at least stopped while the user viewing comments and interacting with comments.

Thank you!

**Comment by ris58h** [comment]
Hi. Sorry for late response.
It's because there is no video preview tooltip available in YT player at this state. Comment preview is placed inside the tooltip. So no tooltip - no preview.

**Comment by S-trace** [comment]
Thank you, I got this.
