### ISSUE TITLE
Feature requirements

### ISSUE THREAD

**Issue by zeref-dragneel** [ris58h/youtube-timestamps#27]
Can you update the pop-up on the right side?

<img src="https://i.imgur.com/4KBfmEt.png)" height="280">

Let's make it look like this

<img src="https://i.imgur.com/4iBSOZ1.png)" height="280">

Small old pop-ups are difficult to see and require you to move the mouse into the new time stamp that shows up

<img src="https://i.imgur.com/38hoCji.png)" height="280">

Design it out loud and place it in the right position to make it easier to see. Thank you very much.

<img src="https://i.imgur.com/27Ryepb.png)" height="280">

**Comment by ris58h** [comment]
Thank you for your feedback.

The extension is about comments, not chapters.
I see some disadvantages in the proposed chapters-like design:
1. It's not clear how to view a whole comment (it could be really long).
2. It's not possible to see the comments in the fullscreen mode.

**Comment by zeref-dragneel** [comment]
Thank you for your prompt reply
