### ISSUE TITLE
Open comment on click

### ISSUE THREAD

**Issue by Spp595** [ris58h/youtube-timestamps#35]
I would like to have the function of opening a comment by pressing a key. It happens under a comment and a discussion starts, but this comment is very difficult to find

**Comment by ris58h** [comment]
Great idea but I can't wrap my head around a possible UX. We could open a video (edit: page) with the comment in a new tab though...

**Comment by Spp595** [comment]
> Great idea but I can't wrap my head around a possible UX. We could open a video with the comment in a new tab though...

It would be great

**Comment by foxydevloper** [comment]
This would be awesome! I'd love to use this extension for finding people who ask things like "what song is playing at this timestamp?" and stuff in case someone already got an answer, but not being able to view the comment doesn't let me do that

**Comment by ris58h** [comment]
I'm working on a prototype right now. I've added a context menu that appears on right-click on a timestamp. The menu items are like on mobile YT version (Reply, Like, Dislike, Report). Any thoughts?

<img width="829" alt="Screenshot 2023-09-18 at 20 29 10" src="https://github.com/ris58h/youtube-timestamps/assets/511242/eadf942d-1a32-4d08-b416-e5581b113d54">

**Comment by Spp595** [comment]
does the reply button take you to the bottom of the comment?

**Comment by ris58h** [comment]
@Spp595 right now it doesn't do anything but it's a good question. I believe that scroll to comment is pretty hard to implement because comments could be not loaded yet or the comment could be on the 5th page. I see two options here:
1. Open a link on the comment in a new tab (maybe the text should be `Show` instead of `Reply`).
2. Open reply dialog like it's done on the mobile version.

**Comment by Spp595** [comment]
I think it's better to open the window in a new tab, it will work for everyone without problems

**Comment by ris58h** [comment]
I have a working prototype in [issue35](https://github.com/ris58h/youtube-timestamps/tree/issue35) branch. It adds a context menu that's available on right-click on a timestamp. RN there is just one option `Open in New Tab` that opens the same video with the comment highlighted in the comments section in a new tab.

@Spp595 @foxydevloper could you check it?

**Comment by foxydevloper** [comment]
I'd check it out but not sure how to install it on firefox from the repository

**Comment by ris58h** [comment]
1. Go to `about:addons` (just copy it and paste it in the URL bar) and disable `YouTube Timestamps` add-on if you have it installed.
2. Download and unzip this version 
[youtube-timestamps-0.8.1.1.zip](https://github.com/ris58h/youtube-timestamps/files/12680251/youtube-timestamps-0.8.1.1.zip)
3. Go to `about:debugging#/runtime/this-firefox` (just copy it and paste it in the URL bar).
4. Click `Load Temporary Add-on` and select `manifest.json` inside the unzipped archive.

To return to the previous state:
1. Remove the temporary loaded add-on on `about:debugging#/runtime/this-firefox` page.
2. Enable `YouTube Timestamps` add-on on `about:addons` page if you disabled it.

**Comment by ris58h** [comment]
Context menu is added in version `0.9.0`. It's already available for Firefox. Chrome version is still on review.

**Comment by foxydevloper** [comment]
> Context menu is added in version `0.9.0`. It's already available for Firefox. Chrome version is still on review.

tried it out, yeah it works 👍

**Comment by ris58h** [comment]
Version `0.9.0` is available in Chrome now.
