### ISSUE TITLE
Extension not working with the following error: TypeError: videoResponse.find is not a function

### ISSUE THREAD

**Issue by Kerst1** [ris58h/youtube-timestamps#39]
Extension stopped working at some point, maybe a few weeks ago. Today I tried disabling all other extensions and it still didn't work so I took this screenshot of the error message I found in the Console when loading a Youtube video:
![yt timestamps error](https://github.com/ris58h/youtube-timestamps/assets/56637456/7bb74e16-c166-4915-879c-e9520cfbf19f)

Firefox version: 124.0.2 (64-bit) - (Up to date)

**Comment by ris58h** [comment]
Duplicates #37

**Comment by ris58h** [comment]
The issue is already fixed (it duplicates #37) but there is another one (#38) that breaks the extension. Unfortunately I haven't found a way to fix it yet.

**Comment by ris58h** [comment]
@Kerst1 should be fixed in version 0.9.1.
I've just uploaded it so it's on review in stores right now.
